
name: Linux Build
on: workflow_dispatch
jobs:
  build:
    name: Linux Build
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Haxe Setup
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.4
      - name: Restore Previous Cache
        uses: actions/cache@v3
        with:
          key: cache-build-linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          restore-keys: |
            cache-build-linux
      - name: Installing/Updating libraries
        run: |
          haxelib setup C:/haxelib
          sudo apt-get install libvlc-dev libvlccore-dev
          haxe -cp ./setup -D analyzer-optimize -main Main --interp
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Building the game
        run: |
          haxelib run lime build linux
      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4
        with:
          name: linuxBuild
          path: export/release/linux/bin
      - name: Clear Previous Cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-linux") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Save Current Cache
        uses: actions/cache@v3
        with:
          key: cache-build-linux
          path: |
            .haxelib/
            export/release/linux/haxe/
            export/release/linux/obj/
          restore-keys: |
  