
name: Mac Build
on: workflow_dispatch
jobs:
  build:
    name: Mac Build
    permissions: write-all
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Haxe Setup
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
      - name: Restore Previous Cache
        uses: actions/cache@v3
        with:
          key: cache-build-macos
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-macos
      - name: Installing/Updating libraries
        run: |
          haxelib setup ~/haxelib
          haxe -cp ./setup -D analyzer-optimize -main Main --interp
          haxelib install hxcpp-debug-server
          haxelib list
      - name: Compile
        run: |
          haxelib run lime build mac
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macBuild
          path: export/release/macos/bin
      - name: Clear Previous Cache
        uses: actions/github-script@v6
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-macos") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Save Current Cache
        uses: actions/cache@v3
        with:
          key: cache-build-macos
          path: |
            .haxelib/
            export/release/macos/haxe/
            export/release/macos/obj/
          restore-keys: |
            cache-build-macos